version: "3"

services:

  mysql:
    container_name: mysql_master_1
    build: ../mysql
    volumes:
      - ../mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ../mysql/data:/var/lib/mysql
      - ../mysql/init:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    ports:
      - 3306:3306
    restart: always